apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rj10
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rj10
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rj10
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rj10
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rj10
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wupf-tenant/rhtap-demo-app/hacbs-test-project-rj10@sha256:bf5a5fd60e67e0f6a932a3f3eb32e69e9f7cdd0440332c30b7f67ec36f8e9bc9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
